version: "2.3"
services:
    nginx:
        image: nginx:alpine
        ports:
            - 8080:80
        labels:
            application: myapp
            service: nginx
        logging:
            driver: splunk
            options:
                splunk-url: $DEMO_SPLUNK_URL
                splunk-token: $DEMO_SPLUNK_TOKEN
                splunk-index: $DEMO_SPLUNK_INDEX
                splunk-format: json
                splunk-insecureskipverify: "1"    # required if using free tier splunk
                labels: application,service 
