version: "2.3"
services:
    docker-stats:
        image: campbel/docker-stats:latest
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        labels:
            application: docker
            service: stats
        logging:
            driver: splunk
            options:
                splunk-url: $DEMO_SPLUNK_URL
                splunk-token: $DEMO_SPLUNK_TOKEN
                splunk-index: $DEMO_SPLUNK_INDEX
                splunk-format: json
                splunk-insecureskipverify: "1"
                labels: application,service
